language: generic
sudo: false
services:
- docker
env:
  global:
  - secure: aUTKskuviFRSkvG9ikwklunjx1EYEv8Veqa8EK7LrQIz87D8y9tqeuEhxHsVlg2MrAcNPisidgrv77RADe0rz95pwkv8B1AvR9H0Mji8OfQzzsjXHsrWoBteJCkmb5RZ8mcwLjZLeVZDIgkDLaKzGXy43+qZO3sCzZSDfUahVXQM3AbrlLTwlVhOeFlmI7yDWWAKBCzQQqVVd0ACWAjMWQcjeIwgJTGDN8eKXkO8wkgFq7HKhp/6GiMiIZEd2Rto93rotfmhgKyNWhSTUxkrQk+WnHTQo4YBTdJ3phtDSCwJaOvUdAXf0xQv4NOAAq1cE1fVKGxlLFVrK2ouXs1SkQYTdACkaDP/dBHzEnglQmUGz7n08K9cpLVBDdPnfumW8uzbD65ZnuTAitgAJ+j3n/Qi6Gw6etImmogDa+w2HhUCxg6Vst4Uat3BGbnh+KvMyULJKpzDiHLDalmj1r4Q4q+mL7ZspxpUkzqndoaXiFdD9xaTr7siHPOxRLt2h/zpNTzlyd5yFQGpnxFY+tRD0AnOcn+YkiUTLFmFhP49fLG+LyiEhYYSZsagE6nCy1CS0P+ZC7K0ffAWExlMtxuptGJz8r8ruPCmLC/EP6yxPKS5AwmBGnJLD+MZy6k5W/W4Mow0ONwIqrqAcp3j8asGyz85xbsiM2nil20erF2IHyA=
  - secure: ii/U6ZrhwsaOD7XRgS3S8j4sECY97ruy26LFs7uh3o1ujZeeFGEKINzSC6xNqXeJ0bbmb82Wit1NGGvW4VrLooQyoj2vzQPeb2PdAaaN2OzamEkJymIARf7RoVbzhJkT4Z2SvrQz9tRwUNg8waLfTUnA0t5xpe6qbrz4IWJ6+SzGCEVyRRoon6Vi2tD2LeYZUfrc6CFSbLSv9BU1dpSDEyV0VhA0MtKgDRmgh4P03kyiDGoZVN8Ndy04trUUHsHVfnJOnMTU9ocI/6QuTGiOC9vI8jXJwl2fkpWI6p2YHmDbYTIAxfHfU3A2AvBmabJuqwUXJ2U8Ieu4ctTlzlZ5Tr7qG70/ZKqjzXdQnkU0ICqqtrKWjT+1/NtWsCHI257Fdg/ytEmH4ZgsCN1oGH3tdN3m7JXgEEjPXovm5ZdX0hN0nFgZbXbzPguii5VRUtYl76c71JVZbcxUDj0Mdj2OOxkMIAG4WUtumX4yiybZbHmwXuETTiILnY08emRiyK1rx0Jgydw1eKI2RxJUDSyo7jJYsD+NLm5JO8YmflSNYrdCJZsZiyKaaLpvTNZ4J3j+01XnnKpyYkzhnDjmv7JeKw0tarRBvVj3Tgy3YEZiONIXuDrurGEz6/wq0ctN0gT21zXTO1vOzvJ0qud14cuRJ7g9Z/jQ6xRFag0zUkrUF2g=
before_deploy:
- sh build-image.sh ${TRAVIS_TAG} build
deploy:
- provider: script
  script: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"  && sh build-image.sh ${TRAVIS_TAG} deploy
  on:
    repo: anz-bank/syslgen-examples
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
