package todos

//
//    THIS IS AUTOGENERATED BY syslgen
//

import (
	"net/http"
)

// ServiceInterface for Todos
type ServiceInterface interface {
	GetComments(PostID string) (int, map[string]string, *Posts)
	GetPosts() (int, map[string]string, *Posts)
	GetTodosID(ID string) (int, map[string]string, *Todo)
	PostComments(newPost Post) (int, map[string]string, *Post)
	IsAuthorized(r *http.Request, authHeader string) bool
	GetErrorResponse(statusCode int, message string, errObj error) interface{}
}
