package todos

//
//    THIS IS AUTOGENERATED BY syslgen
//

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"time"

	restlib "github.com/anz-bank/syslgen-examples/lib"
	"github.com/rickb777/date"
)

// Reference imports to suppress unused errors
var _ = time.Parse

// Reference imports to suppress unused errors
var _ = date.Parse

// Post ...
type Post struct {
	Body   string `json:"body"`
	ID     int64  `json:"id"`
	Title  string `json:"title"`
	UserID int64  `json:"userId"`
}

// Todo ...
type Todo struct {
	Completed bool   `json:"completed"`
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	UserID    int64  `json:"userId"`
}

// Posts ...
type Posts []Post

// Service interface for Todos
type Service interface {
	GETComments(ctx context.Context, headers map[string]string, postid int64) (*restlib.HTTPResult, error)
	GETPosts(ctx context.Context, headers map[string]string) (*restlib.HTTPResult, error)
	GETTodosID(ctx context.Context, headers map[string]string, id int64) (*restlib.HTTPResult, error)
	POSTComments(ctx context.Context, headers map[string]string) (*restlib.HTTPResult, error)
}

// Client for Todos API
type Client struct {
	client *http.Client
	url    string
}

// NewClient for Todos
func NewClient(client *http.Client, serviceURL string) *Client {
	return &Client{client, serviceURL}
}

// GETComments ...
func (s *Client) GETComments(ctx context.Context, headers map[string]string, postid int64) (*restlib.HTTPResult, error) {
	required := []string{}
	responses := []interface{}{&Posts{}}
	u, err := url.Parse(fmt.Sprintf("%s/comments", s.url))
	if err != nil {
		return nil, err
	}
	q := u.Query()
	q.Add("postId", fmt.Sprintf("%v", postid))
	u.RawQuery = q.Encode()
	return restlib.DoHTTPRequest(ctx, s.client, "GET", u.String(), nil, headers, required, responses)
}

// GETPosts ...
func (s *Client) GETPosts(ctx context.Context, headers map[string]string) (*restlib.HTTPResult, error) {
	required := []string{}
	responses := []interface{}{&Posts{}}
	u, err := url.Parse(fmt.Sprintf("%s/posts", s.url))
	if err != nil {
		return nil, err
	}
	q := u.Query()
	u.RawQuery = q.Encode()
	return restlib.DoHTTPRequest(ctx, s.client, "GET", u.String(), nil, headers, required, responses)
}

// GETTodosID ...
func (s *Client) GETTodosID(ctx context.Context, headers map[string]string, id int64) (*restlib.HTTPResult, error) {
	required := []string{}
	responses := []interface{}{&Todo{}}
	u, err := url.Parse(fmt.Sprintf("%s/todos/%v", s.url, id))
	if err != nil {
		return nil, err
	}
	q := u.Query()
	u.RawQuery = q.Encode()
	return restlib.DoHTTPRequest(ctx, s.client, "GET", u.String(), nil, headers, required, responses)
}

// POSTComments ...
func (s *Client) POSTComments(ctx context.Context, headers map[string]string) (*restlib.HTTPResult, error) {
	required := []string{}
	responses := []interface{}{&Post{}}
	u, err := url.Parse(fmt.Sprintf("%s/comments", s.url))
	if err != nil {
		return nil, err
	}
	q := u.Query()
	u.RawQuery = q.Encode()
	return restlib.DoHTTPRequest(ctx, s.client, "POST", u.String(), nil, headers, required, responses)
}
