package todos

//
//    THIS IS AUTOGENERATED BY syslgen
//

import (
	"context"
	"errors"
	"net/http"
)

// DefaultTodosImpl  ...
type DefaultTodosImpl struct {
}

// NewDefaultTodosImpl for Todos
func NewDefaultTodosImpl() *DefaultTodosImpl {
	return &DefaultTodosImpl{}
}

// ServiceInterface for Todos
type ServiceInterface interface {
	GetComments(ctx context.Context, PostID string) (*Posts, int)
	GetPosts(ctx context.Context) (*Posts, int)
	GetTodosID(ctx context.Context, ID string) (*Todo, int)
	PostComments(ctx context.Context, newPost Post) (*Post, int)
	IsAuthorized(r *http.Request, authHeader string) bool
	GetErrorResponse(statusCode int, message string, errObj error) interface{}
}

// GetComments ...
// nolint:gocritic
func (d *DefaultTodosImpl) GetComments(ctx context.Context, PostID string) (*Posts, int) {
	panic(errors.New("not implemented"))
}

// GetPosts ...
// nolint:gocritic
func (d *DefaultTodosImpl) GetPosts(ctx context.Context) (*Posts, int) {
	panic(errors.New("not implemented"))
}

// GetTodosID ...
// nolint:gocritic
func (d *DefaultTodosImpl) GetTodosID(ctx context.Context, ID string) (*Todo, int) {
	panic(errors.New("not implemented"))
}

// PostComments ...
// nolint:gocritic
func (d *DefaultTodosImpl) PostComments(ctx context.Context, newPost Post) (*Post, int) {
	panic(errors.New("not implemented"))
}

// IsAuthorized ...
// nolint:gocritic
func (d *DefaultTodosImpl) IsAuthorized(r *http.Request, authHeader string) bool {
	panic(errors.New("not implemented"))
}

// GetErrorResponse ...
// nolint:gocritic
func (d *DefaultTodosImpl) GetErrorResponse(statusCode int, message string, errObj error) interface{} {
	panic(errors.New("not implemented"))
}
