package todos

//
//    THIS IS AUTOGENERATED BY syslgen
//

import (
	"net/http"
)

// ServiceInterface for Todos
type ServiceInterface interface {
	GetComments(w http.ResponseWriter, PostID string)
	GetPosts(w http.ResponseWriter)
	GetTodosID(w http.ResponseWriter, ID string)
	PostComments(w http.ResponseWriter, newPost Post)
	IsAuthorized(r *http.Request, authHeader string) bool
	SendErrorResponse(w http.ResponseWriter, statusCode int, message string, errObj error)
}
