package todos

//
//    THIS IS AUTOGENERATED BY syslgen
//

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/anz-bank/syslgen-examples/restlib"
)

// Handler interface for Todos
type Handler interface {
	GetCommentsHandler(w http.ResponseWriter, r *http.Request)
	GetPostsHandler(w http.ResponseWriter, r *http.Request)
	GetTodosIDHandler(w http.ResponseWriter, r *http.Request)
	PostCommentsHandler(w http.ResponseWriter, r *http.Request)
}

// ServiceHandler for Todos API
type ServiceHandler struct {
	serviceInterface ServiceInterface
}

// NewServiceHandler for Todos
func NewServiceHandler(serviceInterface ServiceInterface) *ServiceHandler {
	return &ServiceHandler{serviceInterface}
}

// GetCommentsHandler ...
func (s *ServiceHandler) GetCommentsHandler(w http.ResponseWriter, r *http.Request) {
	PostID := restlib.GetQueryParam(r, "postId")
	var ctx context.Context

	Posts, httpStatus := s.serviceInterface.GetComments(ctx, PostID)
	restlib.SendHTTPResponse(w, httpStatus, Posts)
}

// GetPostsHandler ...
func (s *ServiceHandler) GetPostsHandler(w http.ResponseWriter, r *http.Request) {
	var ctx context.Context

	Posts, httpStatus := s.serviceInterface.GetPosts(ctx)
	restlib.SendHTTPResponse(w, httpStatus, Posts)
}

// GetTodosIDHandler ...
func (s *ServiceHandler) GetTodosIDHandler(w http.ResponseWriter, r *http.Request) {
	ID := restlib.GetURLParam(r, "id")
	var ctx context.Context

	Todo, httpStatus := s.serviceInterface.GetTodosID(ctx, ID)
	restlib.SendHTTPResponse(w, httpStatus, Todo)
}

// PostCommentsHandler ...
func (s *ServiceHandler) PostCommentsHandler(w http.ResponseWriter, r *http.Request) {
	decoder := json.NewDecoder(r.Body)
	var newPost Post

	decodeErr := decoder.Decode(&newPost)
	if decodeErr != nil {
		errResp := s.serviceInterface.GetErrorResponse(http.StatusBadRequest, "Error reading request body", decodeErr)
		restlib.SendHTTPResponse(w, http.StatusBadRequest, errResp)
		return
	}

	var ctx context.Context

	Post, httpStatus := s.serviceInterface.PostComments(ctx, newPost)
	restlib.SendHTTPResponse(w, httpStatus, Post)
}
