package todos

//
//    THIS IS AUTOGENERATED BY sysl
//

import (
	"time"

	"github.com/rickb777/date"
)

// Reference imports to suppress unused errors
var _ = time.Parse

// Reference imports to suppress unused errors
var _ = date.Parse

// Post ...
type Post struct {
	Body   string `json:"body"`
	ID     int64  `json:"id"`
	Title  string `json:"title"`
	UserID int64  `json:"userId"`
}

// Todo ...
type Todo struct {
	Completed bool   `json:"completed"`
	ID        int64  `json:"id"`
	Title     string `json:"title"`
	UserID    int64  `json:"userId"`
}

// Posts ...
type Posts []Post
